monitoring_insolvenci/core/views.py
from flask import Blueprint, render_template
from flask_migrate import upgrade

from monitoring_insolvenci.extensions import db
from monitoring_insolvenci.users.models import User

core = Blueprint('core', __name__)


# Obsluha zobrazeni domovske stranky
@core.route('/', methods=['GET'])
def index():
    return render_template('index.html', title='Monitoring insolvencí')


# Obsluha zobrazeni stranky o nas
@core.route('/about', methods=['GET'])
def about():
    return render_template('about.html', title='O nás')


# CLI nasazeni apliakce a vytvoreni hlavniho administratora aplikace
@core.cli.command()
def deploy():
    upgrade()
    admin = User.query.filter_by(id=1).first()
    if not admin:
        admin = User('admin@admin.admin', 'Main', 'Admin', "12345pass")
        admin.toggle_admin()
        db.session.add(admin)
        db.session.commit()

monitoring_insolvenci/insolvencies/views.py
import datetime

from flask import render_template, Blueprint
from flask_login import login_required, current_user

from monitoring_insolvenci.emails.email_sender import send_email
from monitoring_insolvenci.extensions import db
from monitoring_insolvenci.insolvencies.isir2 import Isir, fill_insolvency_with_isir
from monitoring_insolvenci.insolvencies.models import Insolvency
from monitoring_insolvenci.partners.models import Partner
from monitoring_insolvenci.users.models import User

insolvencies = Blueprint('insolvencies', __name__)


# Obsluha zobrazeni vsech insolvenci sledovanych partneru uzivatele
@insolvencies.get('/')
@login_required
def user_insolvencies():
    return render_template('user_insolvencies.html', title='Sledované insolvence partnerů', user=current_user)


# CLI Aktualizace insolvenci
@insolvencies.cli.command()
def update_insolvencies():
    isir = Isir()
    insolvencies_for_notification = {}
    all_partners = Partner.query.all()
    for partner in all_partners:
        insolvencies_for_ico = isir.get_ico_insolvencies(partner.ico)
        if insolvencies_for_ico:
            for insolvency_data in insolvencies_for_ico:
                existing_insolvency = Insolvency.query.filter_by(ico=partner.ico, case=insolvency_data['bcVec'],
                                                                 year=insolvency_data['rocnik']).first()
                if existing_insolvency is None:
                    insolvency = fill_insolvency_with_isir(insolvency_data)
                    insolvency.partner.append(partner)
                    db.session.add(insolvency)
                    db.session.commit()
                    insolvencies_for_notification[insolvency.id] = {'time': insolvency.created,
                                                                    'type': 'new',
                                                                    'new_data': insolvency.to_dict()
                                                                    }
                else:
                    update_data = existing_insolvency.update_insolvency(insolvency_data)
                    if update_data is not False:
                        insolvencies_for_notification[existing_insolvency.id] = update_data
                        db.session.commit()
    users = User.query.all()
    for user in users:
        notification = {}
        for partner in user.partners:
            for insolvency in partner.insolvencies:
                if insolvency.id in insolvencies_for_notification:
                    if partner.id not in notification:
                        notification[partner.id] = {}
                        notification[partner.id]['name'] = partner.name
                        notification[partner.id]['ico'] = partner.ico
                        notification[partner.id]['insolvencies'] = {}
                    notification[partner.id]['insolvencies'][insolvency.id] = insolvencies_for_notification[
                        insolvency.id]
        if len(notification) != 0:
            send_email(user.email, 'Změny v insolvencích k {}'.format(datetime.date.today().strftime("%d.%m.%Y")),
                       'email/update_insolvencies',
                       title='Změny v insolvencích k {}'.format(datetime.date.today().strftime("%d.%m.%Y")), user=user,
                       notification=notification)

monitoring_insolvenci/partners/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort
from flask_login import login_required, current_user

from monitoring_insolvenci.extensions import db
from monitoring_insolvenci.partners.ares import get_ares_data, fill_partner_with_ares
from monitoring_insolvenci.partners.forms import PartnerForm, ImportPartnerForm
from monitoring_insolvenci.partners.models import Partner

partners = Blueprint('partners', __name__)


# Obsluha zobrazeni vsech sledovanych partneru uzivatele
@partners.route('/', methods=['GET'])
@login_required
def user_partners():
    return render_template('user_partners.html', title='Sledovaní partneři')


# Obsluha pridani jednoho partnera do sledovani
@partners.route('/create', methods=['GET', 'POST'])
@login_required
def create_partner():
    form = PartnerForm()
    if form.validate_on_submit():
        partner = Partner.query.filter_by(ico=form.ico.data).first()
        if partner:
            if current_user not in partner.users:
                partner.users.append(current_user)
                partner.active = True
        else:
            partner_ares = get_ares_data(form.ico.data)
            if partner_ares:
                partner = fill_partner_with_ares(partner_ares)
                partner.users.append(current_user)
                db.session.add(partner)
            else:
                flash('Chyba IČO, nebo problém ve zpracování.', "warning")
                return render_template('form_create_partner.html', title='Vytvoření partnera', form=form)
        db.session.commit()
        flash('Partner vytvořen.', 'success')
        return redirect(url_for('partners.partner_detail', partner_id=partner.id))
    elif request.method != 'GET':
        flash('Chyba IČO, nebo problém ve zpracování.', "warning")
    return render_template('form_create_partner.html', title='Vytvoření partnera', form=form)


# Obsluha hromadneho importu partneru do sledovani
@partners.route('/import', methods=['GET', 'POST'])
@login_required
def import_partners():
    form = ImportPartnerForm()
    if form.validate_on_submit():
        file = form.file.data
        for line in file:
            line = line.strip().decode("utf-8")
            partner = Partner.query.filter_by(ico=line).first()
            if partner:
                if current_user not in partner.users:
                    partner.users.append(current_user)
                    partner.active = True
            else:
                partner_ares = get_ares_data(line)
                if partner_ares:
                    partner = fill_partner_with_ares(partner_ares)
                    partner.users.append(current_user)
                    db.session.add(partner)
            db.session.commit()
        return redirect(url_for('partners.user_partners'))
    return render_template('form_import_partners.html', title='Import partnerů', form=form)


# Obsluha zobrazeni detailu partnera
@partners.get('/detail/', defaults={'partner_id': ''})
@partners.route('/detail/<int:partner_id>', methods=['GET', 'POST'])
@login_required
def partner_detail(partner_id):
    partner = Partner.query.get_or_404(partner_id)
    if current_user not in partner.users:
        abort(403)
    return render_template('partner_detail.html', title='Detail partnera: {}'.format(partner.ico), partner=partner)


# Obsluha odebrani partnera ze sledovani
@partners.post('/detail/<int:partner_id>/delete')
@login_required
def delete_partner(partner_id):
    partner = Partner.query.get_or_404(partner_id)
    if current_user not in partner.users:
        abort(403)
    partner.remove_user(current_user)
    if len(partner.users) == 0:
        partner.toggle_active()
    db.session.commit()
    flash('Partner {} smazán.'.format(partner.name), 'success')
    return redirect(url_for('partners.user_partners'))

monitoring_insolvenci/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, Markup, abort
from flask_login import login_user, current_user, logout_user, login_required

from monitoring_insolvenci.emails.email_sender import send_email
from monitoring_insolvenci.extensions import db
from monitoring_insolvenci.users.forms import RegistrationForm, LoginForm, UpdateUserForm, GenerateApiTokenForm
from monitoring_insolvenci.users.models import User

users = Blueprint('users', __name__)


# Obsluha registrace uzivatele
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, first_name=form.first_name.data, last_name=form.last_name.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Děkujeme za registraci.', 'success')
        send_email(user.email, 'Vítejte na Monitoring insolvencí', 'email/register_email',
                   title="Děkujeme za registraci!", user=user)
        login_user(user)
        return redirect(url_for('partners.user_partners'))
    return render_template('form_register.html', title='Registrace', form=form)


# Obsluha prihlaseni uzivatele
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.password_check(form.password.data):
            if user.active:
                login_user(user)
                next_page = request.args.get('next')
                if next_page is None or not next_page[0] == '/':
                    next_page = url_for('core.index')
                flash('Byly jste úspěšně přihlášeni.', 'success')
                return redirect(next_page)
            else:
                flash(Markup('Účet je zablokován, požádejte administrátora o aktivaci!'), 'danger')
        else:
            flash(Markup(
                'Chybný email nebo heslo! Pokud ještě účet nemáte, neváhejte se <a href="{}" '
                'class="alert-link">registrovat</a>!'.format(
                    url_for('users.register'))), 'danger')
    return render_template('form_login.html', title='Přihlášení', form=form)


# Obsluha odhlaseni uzivatele
@users.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    flash('Byly jste úspěšně odhlášeni.', 'success')
    return redirect(url_for('core.index'))


# Obsluha editace uzivatele
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        current_user.email = form.email.data
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        db.session.commit()
        flash('Uživatelský účet byl aktualizován.', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.email.data = current_user.email
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
    return render_template('form_account.html',
                           title='Uživatelský účet: {} {}'.format(current_user.first_name, current_user.last_name),
                           form=form)


# Obsluha generovani API tokenu uzivatele
@users.route('/apitoken', methods=['GET', 'POST'])
@login_required
def api_token():
    form = GenerateApiTokenForm()
    if form.validate_on_submit():
        token = current_user.token
        flash('API Token je zobrazen, překopírujte si ho.', 'success')
        form.token.data = token
    elif request.method == 'GET':
        form.token.data = '********************************'
    return render_template('form_apitoken.html', form=form)


# Obsluha administrace uzivatelu
@users.route('/administration', methods=['GET'])
@login_required
def administration():
    if not current_user.admin:
        abort(403)
    return render_template('user_administration.html', title='Administrace uživatelů')


# Obsluha zmeny parametru admin u uzivatele
@users.post('/detail/<int:user_id>/toogle_admin')
@login_required
def toggle_admin(user_id):
    user = User.query.get_or_404(user_id)
    if not current_user.admin or current_user is user or user.id == 1:
        abort(403)
    user.toggle_admin()
    if user.admin:
        flash('Uživatel {} {} nastaven administrátorem.'.format(user.first_name, user.last_name), 'success')
    else:
        flash('Uživatel {} {} odebrán z administrátorů.'.format(user.first_name, user.last_name), 'success')
    return redirect(url_for('users.administration'))


# Obsluha zmeny parametru active u uzivatele
@users.post('/detail/<int:user_id>/toogle_active')
@login_required
def toogle_active(user_id):
    user = User.query.get_or_404(user_id)
    if not current_user.admin or current_user is user or user.id == 1:
        abort(403)
    user.toggle_active()
    if user.admin:
        flash('Uživatel {} {} zaktivněn.'.format(user.first_name, user.last_name), 'success')
    else:
        flash('Uživatel {} {} zneaktivněn.'.format(user.first_name, user.last_name), 'success')
    return redirect(url_for('users.administration'))

monitoring_insolvenci/templates/about.html
{% extends "base.html" %}
{% block content %}
    <div class="px-4 pt-2 my-3 text-center">
        <h1>O nás</h1>
    </div>
    <div class="container">
        <h3>O aplikaci</h3>
        <p class="lead">
            Tato webová aplikace byla vytvořena v rámci bakalářské práce. Jejím cílem bylo představit vývoj webových
            aplikací v jazyce Python 3.
        </p>
        <p class="lead">
            Apliakce umožňuje uživatelům sledovat obchodní partnery a jejich insolvenční řízení. Data partnerů jsou
            odebírána s veřejného zdroje ARES. Data insolvenčních řízení jsou odebírána z veřejného zdroje Insolvenční
            rejstřík.
        </p>
        <h3>Použité technologie</h3>
        <p class="lead">
            Aplikace využívá v maximálních možnostech jazyk Python 3 s frameworkem Flask a šablonovacím jazykem Jinja2
            nad
            HTML.
        </p>
        <p class="lead">
            Pro moderní vzhled jsou použity CSS a JS knihovny Bootstrap a Datatables.
        </p>
    </div>
{% endblock %}

monitoring_insolvenci/templates/base.html
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8"/>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta content="Filip Hanš" name="author"/>
    <title>{{ title }}</title>
    <link
            href="{{ url_for('static', filename='favicon.ico') }}"
            rel="shortcut icon"
    />
    <link
            crossorigin="anonymous"
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
            rel="stylesheet"
    />
    {% block csss %} {% endblock %}
</head>
<body class="d-flex flex-column min-vh-100">
<header class="navbar navbar-expand-md navbar-light bd-navbar bg-light border-bottom py-3 mb-4">
    <nav class="container-xxl flex-wrap flex-md-nowrap">
        <a class="navbar-brand" href="{{ url_for('core.index') }}">
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                 class="bi bi-journal-check" viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                      d="M10.854 6.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 8.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z"/>
                <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z"/>
            </svg>
        </a>
        <button aria-controls="navbarCollapse" aria-expanded="false" aria-label="Menu" class="navbar-toggler"
                data-bs-target="#navbarCollapse" data-bs-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav bd-navbar-nav pt-2 py-md-0">
                <li class="nav-item col-6 col-md-auto">
                    <a aria-current="page" class="nav-link" href="{{ url_for('core.index') }}">Domů</a>
                </li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item col-6 col-md-auto">
                        <a class="nav-link" href="{{ url_for('partners.user_partners') }}">Partneři</a>
                    </li>
                    <li class="nav-item col-6 col-md-auto">
                        <a class="nav-link" href="{{ url_for('insolvencies.user_insolvencies') }}">Insolvence</a>
                    </li>
                    {% if current_user.admin %}
                        <li class="nav-item col-6 col-md-auto">
                            <a class="nav-link" href="{{ url_for('users.administration') }}">Administrace uživatelů</a>
                        </li>
                    {% endif %}
                {% endif %}
                <li class="nav-item col-6 col-md-auto">
                    <a class="nav-link" href="{{ url_for('core.about') }}">O nás</a>
                </li>
            </ul>
            <hr class="d-md-none text-white-50">
            <ul class="navbar-nav flex-row flex-wrap ms-md-auto">
                {% if current_user.is_authenticated %}
                    <li class="d-flex nav-item dropdown">
                        <a aria-expanded="false" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"
                           id="logedInNavbarDropdownMenuLink" role="button">
                            {{ current_user.first_name }} {{ current_user.last_name }}
                        </a>
                        <ul aria-labelledby="logedInNavbarDropdownMenuLink" class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item" href="{{ url_for('users.account') }}">Profil</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('users.api_token') }}">API Token</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('users.logout') }}">Odhlásit</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="d-flex nav-item dropdown">
                        <a aria-expanded="false" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"
                           id="anonymNavbarDropdownMenuLink" role="button">
                            Účet
                        </a>
                        <ul aria-labelledby="anonymNavbarDropdownMenuLink" class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item" href="{{ url_for('users.login') }}">Přihlásit</a></li>
                            <li><a class="dropdown-item" href="{{ url_for('users.register') }}">Registrovat</a></li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>
<main>
    <div class="container">
        {% for category, message in get_flashed_messages(with_categories=true) %}
            <div
                    class="alert alert-{{ category }} alert-dismissible fade show"
                    role="alert"
            >
                {{ message }}
                <button
                        aria-label="Close"
                        class="btn-close"
                        data-bs-dismiss="alert"
                        type="button"
                ></button>
            </div>
        {% endfor %}
        {% block content %}
        {% endblock %}
    </div>
</main>
<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted">Vytvořeno jako praktická část bakalářské práce. Autor: Filip Hanš</span>
    </div>
</footer>
<script
        crossorigin="anonymous"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
></script>
{% block scripts %} {% endblock %}
</body>
</html>

monitoring_insolvenci/templates/form_account.html
{% extends "base.html" %}
{% block content %}
    <div class="px-4 pt-2 my-3 text-center">
        <h1>Úprava profilu</h1>
    </div>
    <div class="container text-center" style="max-width: 400px;">
        <form action="" enctype="multipart/form-data" method="POST">
            {{ form.hidden_tag() }}
            <div class="form-floating">
                {{ form.first_name(class='form-control', placeholder="Jméno") }}
                {{ form.first_name.label(class='form-group') }}
            </div>
            <div class="form-floating">
                {{ form.last_name(class='form-control', placeholder="Příjmení") }}
                {{ form.last_name.label(class='form-group') }}
            </div>
            <div class="form-floating mb-3">
                {{ form.email(class='form-control', placeholder="name@example.com") }}
                {{ form.email.label(class='form-group') }}
            </div>
            {{ form.submit(class='btn btn-primary btn-lg') }}
        </form>
    </div>
{% endblock %}

monitoring_insolvenci/templates/form_apitoken.html
{% extends "base.html" %}
{% block content %}
    <div class="px-4 pt-2 my-3 text-center">
        <h1>Generování API Tokenu</h1>
    </div>
    <div class="container text-center" style="max-width: 850px;">
        <form action="" enctype="multipart/form-data" method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.token(class='text-center form-control', placeholder='API Token', disabled=True, readonly=True) }}
            </div>
            {{ form.submit(class='btn btn-primary btn-lg') }}
        </form>
    </div>
{% endblock %}

monitoring_insolvenci/templates/form_create_partner.html
{% extends "base.html" %}
{% block content %}
    <div class="px-4 pt-2 my-3 text-center">
        <h1>Vytvoření partnera</h1>
    </div>
    <div class="container text-center" style="max-width: 400px;">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-floating mb-3">
                {{ form.ico(type="text", class="form-control", placeholder="00000000") }}
                {{ form.ico.label(class='form-label') }}
            </div>
            {{ form.submit(class="btn btn-primary btn-lg") }}
        </form>
    </div>
{% endblock %}

monitoring_insolvenci/templates/form_import_partners.html
{% extends "base.html" %}
{% block content %}
    <div class="px-4 pt-2 my-3 text-center">
        <h1>Import partnerů ze souboru</h1>
    </div>
    <div class="container text-center" style="max-width: 400px;">
        <form enctype="multipart/form-data" method="POST" class="importPartnerForm">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.file(type="file", class="form-control", placeholder="soubor.txt") }}
            </div>
            {{ form.submit(class="btn btn-primary btn-lg btnImport") }}
        </form>
        <a href="{{ url_for('static', filename='sablona_importu_partneru.txt') }}">Šablona pro import ke stažení</a>
    </div>
{% endblock %}

monitoring_insolvenci/templates/index.html
{% extends "base.html" %}
{% block content %}
    {% if current_user.is_authenticated %}
        <div class="px-4 pt-2 my-3 text-center">
            <h1>{{ current_user.first_name }} {{ current_user.last_name }}</h1>
            <div class="col-lg-6 mx-auto">
                <p class="lead mb-4">Aplikace pro Vás sleduje {{ current_user.partners.count() }} partnerů.</p>
                <div aria-label="controls" class="btn-group flex-wrap" role="group">
                    <form action="{{ url_for('partners.user_partners') }}" method="get">
                        <input class="btn btn-primary btn-lg" type="submit" value="Partneři"/>
                    </form>
                    <form action="{{ url_for('insolvencies.user_insolvencies') }}" method="get">
                        <input class="btn btn-secondary btn-lg" type="submit" value="Insolvence"/>
                    </form>
                </div>
            </div>
        </div>
    {% else %}
        <div class="px-4 pt-2 my-3 text-center">
            <h1>Monitoring insolvencí</h1>
            <div class="col-lg-6 mx-auto">
                <p class="lead mb-4">Aplikace na sledování stavů obchodních partnerů.</p>
            </div>
        </div>
        <div class="row row-cols-1 row-cols-md-3 text-center">
            <div class="col"></div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Zdarma</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Neomezené množství sledovaných partnerů</li>
                        </ul>
                        <form action="{{ url_for('users.register') }}" method="get">
                            <input class="w-100 btn btn-lg btn-primary" type="submit" value="Registrace zdarma"/>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col"></div>
        </div>
    {% endif %}
{% endblock %}

monitoring_insolvenci/templates/user_partners.html
{% extends "base.html" %}
{% block csss %}
    <link
            href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.min.css"
            rel="stylesheet"
            type="text/css"
    />
{% endblock %}
{% block content %}
    <div class="px-4 pt-2 my-3 text-center">
        <h1>Sledovaní partneři</h1>
    </div>
    <div class="row mb-3">
        <div class="col">
            <div aria-label="controls" class="btn-group flex-wrap" role="group">
                <form action="{{ url_for('partners.create_partner') }}" method="get">
                    <input class="btn btn-success" type="submit" value="+ Přidat"/>
                </form>
                <form action="{{ url_for('partners.import_partners') }}" method="get">
                    <input class="btn btn-warning" type="submit" value="++ Přidat hromadně"/>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="table-responsive">
                <table class="table table-hover" id="data" style="width: 100%;">
                    <thead class="table-light">
                    <tr>
                        <th>IČO</th>
                        <th>DIČ</th>
                        <th>Název společnosti</th>
                        <th>Forma podnikání</th>
                        <th>Stav</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="modal fade" id="deletePartner" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLabel">Smazání partnera</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div id="delete-text" class="modal-body">
                    Opravdu chcete smazat partnera?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Ne</button>
                    <form id="delete-form" action="#" method="post">
                        <input class="btn btn-danger" type="submit" value="Ano"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script
            src="https://code.jquery.com/jquery-3.6.0.min.js"
            type="text/javascript"
    ></script>
    <script
            src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"
            type="text/javascript"
    ></script>
    <script
            src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.js"
            type="text/javascript"
    ></script>
    <script
            src="{{ url_for('static', filename='js/user_partners.js') }}"
            type="text/javascript"
    ></script>
    <script type="text/javascript">
        $(document).ready(function () {
            const table = $("#data").DataTable({
                "language": {
                    "url": '//cdn.datatables.net/plug-ins/1.10.25/i18n/Czech.json'
                },
                ajax: "{{ url_for('api_v1.partners_ajax') }}",
                serverSide: true,
                createdRow: function (row, data, dataIndex) {
                    if (data.insolvency_count > 0) {
                        $(row).addClass('table-danger');
                    }
                },
                autoWidth: false,
                columns: [
                    {data: "ico", width: '8%'},
                    {data: "dic", width: '8%'},
                    {data: "name", width: '39%'},
                    {data: "business_form", width: '25%', orderable: false},
                    {data: "state", width: '5%'},
                    {
                        data: "id",
                        width: '50px',
                        className: "",
                        render: function (data, type, row) {
                            return '<div aria-label="controls" class="btn-group flex-wrap" role="group"><form action="{{ url_for('partners.partner_detail') }}' + data + '"method="get" target="_blank"><input class="btn btn-primary" type="submit" value="Detail" /></form><button type="button" class="btn btn-danger partner-delete" data-bs-toggle="modal" data-bs-target="#deletePartner">Smazat</button></div>';
                        },
                        orderable: false
                    },
                ],
            });
            $('#data tbody').on('click', 'tr.even, tr.odd', function (e) {
                var tr = $(this);
                var row = table.row(tr);
                if (row.child.isShown()) {
                    row.child.hide();
                    tr.removeClass('shown');
                } else {
                    row.child(format(row.data())).show();
                    tr.addClass('shown');
                }
            });
            $('#data').on('click', 'button.partner-delete', function (e) {
                var tr = $(this).closest('tr');
                var row = table.row(tr);
                document.getElementById("delete-text").innerHTML = "Opravdu chcete smazat partnera " + row.data().name + " ?";
                document.getElementById("delete-form").action = row.data().del_link;
            });
        });
    </script>
{% endblock %}